// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_Runtime_106866_runtime_106866 = CoreClr.coreclr_test({
    name: "Runtime_106866",
    srcs: ["Runtime_106866.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});
