load("//:defs.bzl", "NETCOREAPP_CURRENT", "csharp_library")

csharp_library(
    name = "ReferencedClassLibNeutralIsSatellite",
    srcs = ["ReferencedClassLibNeutralIsSatellite.cs"],
    target_frameworks = [NETCOREAPP_CURRENT],
    resources = glob(["ReferencedStrings*.resx"]),
    visibility = ["//src/libraries/System.Runtime.Loader/tests:__subpackages__"],
)
