// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const interop_COM_NETServer_nETServer = CoreClr.coreclr_test({
    name: "NETServer",
    srcs: ["ArrayTesting.cs", "ClassInterfaceTesting.cs", "ColorTesting.cs", "ConsumeNETServerTesting.cs", "DispatchCoerceTesting.cs", "DispatchTesting.cs", "ErrorMarshalTesting.cs", "EventTesting.cs", "ImportedTypes.cs", "LicenseTesting.cs", "MiscTypesTesting.cs", "NumericTesting.cs", "StringTesting.cs"],
    tags: ["manual"],
});
