// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_DevDiv_461649_devDiv_461649 = CoreClr.coreclr_test({
    name: "DevDiv_461649",
    srcs: ["DevDiv_461649.cs"],
    optimize: true,
    tags: ["manual"],
});
