// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const async_reflection_reflection_simple = CoreClr.coreclr_test({
    name: "reflection-simple",
    srcs: ["reflection-simple.cs"],
    optimize: true,
    tags: ["manual"],
});
