// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_opt_SVE_conditionalSelectConstants = CoreClr.coreclr_test({
    name: "ConditionalSelectConstants",
    srcs: ["ConditionalSelectConstants.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_predicateInstructions = CoreClr.coreclr_test({
    name: "PredicateInstructions",
    srcs: ["PredicateInstructions.cs"],
    allowUnsafe: true,
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_embeddedLoads = CoreClr.coreclr_test({
    name: "EmbeddedLoads",
    srcs: ["EmbeddedLoads.cs"],
    allowUnsafe: true,
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_changeMaskUse = CoreClr.coreclr_test({
    name: "ChangeMaskUse",
    srcs: ["ChangeMaskUse.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_constantVectors = CoreClr.coreclr_test({
    name: "ConstantVectors",
    srcs: ["ConstantVectors.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_constantMasksOp2Fixed = CoreClr.coreclr_test({
    name: "ConstantMasksOp2Fixed",
    srcs: ["ConstantMasksOp2Fixed.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_constantMasks = CoreClr.coreclr_test({
    name: "ConstantMasks",
    srcs: ["ConstantMasks.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_opt_SVE_maskUse = CoreClr.coreclr_test({
    name: "MaskUse",
    srcs: ["MaskUse.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});
