// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const baseservices_typeequivalence_istypeequivalent_typeequivalenttypes_1 = CoreClr.coreclr_test({
    name: "typeequivalenttypes_1",
    srcs: ["istypeequivalent.cs"],
    tags: ["manual"],
});

@@public
export const baseservices_typeequivalence_istypeequivalent_typeequivalenttypes_2 = CoreClr.coreclr_test({
    name: "typeequivalenttypes_2",
    srcs: ["istypeequivalent.cs"],
    tags: ["manual"],
});
