// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const regressions_coreclr_GitHub_61104_test61104 = CoreClr.coreclr_test({
    name: "test61104",
    srcs: ["test61104.cs"],
    pri: 1,
    tags: ["manual"],
});
