// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_Arm_Sha1_sha1_r = CoreClr.coreclr_test({
    name: "Sha1_r",
    srcs: ["Program.Sha1.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_Arm_Sha1_sha1_ro = CoreClr.coreclr_test({
    name: "Sha1_ro",
    srcs: ["Program.Sha1.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    optimize: true,
    tags: ["manual"],
});
