// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_Runtime_105719_runtime_105719 = CoreClr.coreclr_test({
    name: "Runtime_105719",
    srcs: ["Runtime_105719.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});
