// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const loader_classloader_regressions_dev11_95728_dev11_95728 = CoreClr.coreclr_test({
    name: "dev11_95728",
    srcs: ["dev11_95728.cs"],
    pri: 1,
    size: "medium",
    tags: ["manual"],
});
