// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_Arm_ArmBase_Arm64_armBase_Arm64_r = CoreClr.coreclr_test({
    name: "ArmBase.Arm64_r",
    srcs: ["Program.ArmBase.Arm64.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_Arm_ArmBase_Arm64_armBase_Arm64_ro = CoreClr.coreclr_test({
    name: "ArmBase.Arm64_ro",
    srcs: ["Program.ArmBase.Arm64.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    optimize: true,
    tags: ["manual"],
});
