// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Performance_CodeQuality_Serialization_serialize = CoreClr.coreclr_test({
    name: "Serialize",
    srcs: ["Serialize.cs"],
    debugType: "pdbonly",
    optimize: true,
    tags: ["manual"],
});

@@public
export const jIT_Performance_CodeQuality_Serialization_deserialize = CoreClr.coreclr_test({
    name: "Deserialize",
    srcs: ["Deserialize.cs"],
    debugType: "pdbonly",
    optimize: true,
    tags: ["manual"],
});
