// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_Arm_Crc32_crc32_Arm_r = CoreClr.coreclr_test({
    name: "Crc32.Arm_r",
    srcs: ["Program.Crc32.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_Arm_Crc32_crc32_Arm_ro = CoreClr.coreclr_test({
    name: "Crc32.Arm_ro",
    srcs: ["Program.Crc32.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    optimize: true,
    tags: ["manual"],
});
