// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const loader_binding_tracing_assemblyToLoadDependency = CoreClr.coreclr_test({
    name: "AssemblyToLoadDependency",
    srcs: ["AssemblyToLoadDependency.cs"],
    tags: ["manual"],
});

@@public
export const loader_binding_tracing_binderTracingTest_Basic = CoreClr.coreclr_test({
    name: "BinderTracingTest.Basic",
    srcs: ["BinderTracingTest.Basic.cs", "BinderTracingTest.DefaultProbing.cs"],
    tags: ["manual"],
});

@@public
export const loader_binding_tracing_binderTracingTest_ResolutionFlow = CoreClr.coreclr_test({
    name: "BinderTracingTest.ResolutionFlow",
    srcs: ["BinderTracingTest.EventHandlers.cs", "BinderTracingTest.ResolutionFlow.cs"],
    tags: ["manual"],
});
