// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const readytorun_fieldlayout_fieldlayout = CoreClr.coreclr_test({
    name: "fieldlayout",
    srcs: ["fieldlayouttests.cs"],
    tags: ["manual"],
});
