// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const functionalTests_WebAssembly_Browser_RuntimeConfig_webAssembly_Browser_RuntimeConfig_Test = CoreClr.coreclr_test({
    name: "WebAssembly.Browser.RuntimeConfig.Test",
    srcs: ["Program.cs"],
    tags: ["manual"],
});
