// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_jit64_rtchecks_overflow_overflow01_sub = CoreClr.coreclr_test({
    name: "overflow01_sub",
    srcs: ["overflow01.cs"],
    debugType: "pdbonly",
    defines: ["OP_SUB"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow02_sub = CoreClr.coreclr_test({
    name: "overflow02_sub",
    srcs: ["overflow02.cs"],
    debugType: "pdbonly",
    defines: ["OP_SUB"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow02_add = CoreClr.coreclr_test({
    name: "overflow02_add",
    srcs: ["overflow02.cs"],
    debugType: "pdbonly",
    defines: ["OP_ADD"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow02_div = CoreClr.coreclr_test({
    name: "overflow02_div",
    srcs: ["overflow02.cs"],
    debugType: "pdbonly",
    defines: ["OP_DIV"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow02_mul = CoreClr.coreclr_test({
    name: "overflow02_mul",
    srcs: ["overflow02.cs"],
    debugType: "pdbonly",
    defines: ["OP_MUL"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow04_mul = CoreClr.coreclr_test({
    name: "overflow04_mul",
    srcs: ["overflow04.cs"],
    debugType: "pdbonly",
    defines: ["OP_MUL"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow01_mul = CoreClr.coreclr_test({
    name: "overflow01_mul",
    srcs: ["overflow01.cs"],
    debugType: "pdbonly",
    defines: ["OP_MUL"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow04_sub = CoreClr.coreclr_test({
    name: "overflow04_sub",
    srcs: ["overflow04.cs"],
    debugType: "pdbonly",
    defines: ["OP_SUB"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow04_div = CoreClr.coreclr_test({
    name: "overflow04_div",
    srcs: ["overflow04.cs"],
    debugType: "pdbonly",
    defines: ["OP_DIV"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow03_add = CoreClr.coreclr_test({
    name: "overflow03_add",
    srcs: ["overflow03.cs"],
    debugType: "pdbonly",
    defines: ["OP_ADD"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow01_add = CoreClr.coreclr_test({
    name: "overflow01_add",
    srcs: ["overflow01.cs"],
    debugType: "pdbonly",
    defines: ["OP_ADD"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow03_div = CoreClr.coreclr_test({
    name: "overflow03_div",
    srcs: ["overflow03.cs"],
    debugType: "pdbonly",
    defines: ["OP_DIV"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow04_add = CoreClr.coreclr_test({
    name: "overflow04_add",
    srcs: ["overflow04.cs"],
    debugType: "pdbonly",
    defines: ["OP_ADD"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow01_div = CoreClr.coreclr_test({
    name: "overflow01_div",
    srcs: ["overflow01.cs"],
    debugType: "pdbonly",
    defines: ["OP_DIV"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow03_sub = CoreClr.coreclr_test({
    name: "overflow03_sub",
    srcs: ["overflow03.cs"],
    debugType: "pdbonly",
    defines: ["OP_SUB"],
});

@@public
export const jIT_jit64_rtchecks_overflow_overflow03_mul = CoreClr.coreclr_test({
    name: "overflow03_mul",
    srcs: ["overflow03.cs"],
    debugType: "pdbonly",
    defines: ["OP_MUL"],
});
