// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const loader_CustomAttributes_dynamicObjects = CoreClr.coreclr_test({
    name: "DynamicObjects",
    srcs: ["DynamicObjects.cs"],
    tags: ["manual"],
});
