// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_Runtime_106867_runtime_106867 = CoreClr.coreclr_test({
    name: "Runtime_106867",
    srcs: ["Runtime_106867.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});

@@public
export const jIT_Regression_JitBlue_Runtime_106867_runtime_106867_1 = CoreClr.coreclr_test({
    name: "Runtime_106867_1",
    srcs: ["Runtime_106867_1.cs"],
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});
