load("//:defs.bzl", "NETCOREAPP_CURRENT", "csharp_binary")

csharp_binary(
    name = "TestApp",
    srcs = ["TestApp.cs"],
    msbuild_analyzer_config = "style",
    nullable = "annotations",
    target_frameworks = [NETCOREAPP_CURRENT],
    visibility = ["//src/libraries/System.Runtime/tests:__subpackages__"],
)
