// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const interop_PInvoke_BestFitMapping_Assembly_False_False_assembly_False_False = CoreClr.coreclr_test({
    name: "Assembly_False_False",
    srcs: ["AssemblyInfo.cs", "PInvoke_Default.cs"],
    tags: ["manual"],
});
