// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const tracing_eventpipe_common_Microsoft_Diagnostics_NETCore_Client_microsoft_Diagnostics_NETCore_Client = CoreClr.coreclr_test({
    name: "Microsoft.Diagnostics.NETCore.Client",
    srcs: ["AssemblyInfo.cs", "BinaryWriterExtensions.cs", "DiagnosticsClient/DiagnosticsClient.cs", "DiagnosticsClient/DiagnosticsClientExceptions.cs", "DiagnosticsClient/DumpType.cs", "DiagnosticsClient/EventPipeProvider.cs", "DiagnosticsClient/EventPipeSession.cs", "DiagnosticsClient/EventPipeSessionConfiguration.cs", "DiagnosticsClient/WriteDumpFlags.cs", "DiagnosticsIpc/ExposedSocketNetworkStream.cs", "DiagnosticsIpc/IpcAdvertise.cs", "DiagnosticsIpc/IpcClient.cs", "DiagnosticsIpc/IpcCommands.cs", "DiagnosticsIpc/IpcEndpointConfig.cs", "DiagnosticsIpc/IpcHeader.cs", "DiagnosticsIpc/IpcMessage.cs", "DiagnosticsIpc/IpcResponse.cs", "DiagnosticsIpc/IpcServerTransport.cs", "DiagnosticsIpc/IpcSocket.cs", "DiagnosticsIpc/IpcTcpSocketEndPoint.cs", "DiagnosticsIpc/IpcTransport.cs", "DiagnosticsIpc/IpcUnixDomainSocket.cs", "DiagnosticsIpc/IpcUnixDomainSocketEndPoint.cs", "DiagnosticsIpc/ProcessEnvironment.cs", "DiagnosticsIpc/ProcessInfo.cs", "DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs", "DiagnosticsServerRouter/DiagnosticsServerRouterRunner.cs", "HandleableCollection.cs", "IpcHelpers.cs", "NativeMethods.cs", "ReversedServer/IpcEndpointInfo.cs", "ReversedServer/ReversedDiagnosticsServer.cs", "StreamExtensions.cs"],
    tags: ["manual"],
});
