exports_files(["Assembly1.cs"])

load("//:defs.bzl", "NETCOREAPP_CURRENT", "OPEN_SNK", "csharp_library")

csharp_library(
    name = "System.Diagnostics.FileVersionInfo.TestAssembly",
    srcs = ["Assembly1.cs"],
    target_frameworks = [NETCOREAPP_CURRENT],
    keyfile = OPEN_SNK,
    nullable = "annotations",
    nowarn = [
        # Directory.Build.props IsTestProject NoWarn
        "SYSLIB0011",
        "SYSLIB0050",
        "SYSLIB0051",
        "IL2121",
    ],
    msbuild_analyzer_config = "style",
    interceptors_namespaces = ";Microsoft.Extensions.Validation.Generated",
    visibility = ["//src/libraries/System.Diagnostics.FileVersionInfo/tests:__subpackages__"],
    deps = [
        "//src/libraries:ref_System.Runtime",
    ],
)
