// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_Arm_Rdm_rdm_r = CoreClr.coreclr_test({
    name: "Rdm_r",
    srcs: ["Program.Rdm.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_Arm_Rdm_rdm_ro = CoreClr.coreclr_test({
    name: "Rdm_ro",
    srcs: ["Program.Rdm.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Helpers.cs", "//src/tests/JIT/HardwareIntrinsics/Arm/Shared:Program.cs"],
    optimize: true,
    tags: ["manual"],
});
