load("//src/tests:live_test.bzl", "library_test")
load("//:defs.bzl", "OPEN_SNK")

exports_files([
    "System.Runtime.Tests/System/IndexTests.cs",
    "System.Runtime.Tests/System/RangeTests.cs",
    "System.Runtime.Tests/System/Text/Unicode/Utf8Tests.cs",
    "System.Threading.Tasks.Extensions.Tests/ManualResetValueTaskSourceTests.cs",
    "System.Threading.Tasks.Tests/System.Runtime.CompilerServices/ConfiguredAsyncDisposable.cs",
    "System.Threading.Tasks.Tests/System.Runtime.CompilerServices/ConfiguredCancelableAsyncEnumerableTests.cs",
])

XUNIT_DEPS = [
    "@paket.main//microsoft.dotnet.xunitassert",
    "@paket.main//microsoft.dotnet.xunitextensions",
    "@paket.main//xunit.abstractions",
    "@paket.main//xunit.extensibility.core",
]

library_test(
    name = "System.IO.FileSystem.Primitives.Tests",
    srcs = glob(["System.IO.FileSystem.Primitives.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.IO.FileSystem.Primitives:impl_System.IO.FileSystem.Primitives",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.IO.UnmanagedMemoryStream.Tests",
    srcs = glob(["System.IO.UnmanagedMemoryStream.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.IO.UnmanagedMemoryStream:impl_System.IO.UnmanagedMemoryStream",
        "//src/libraries/Common/tests:StreamConformanceTests",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    allow_unsafe_blocks = True,
    keyfile = OPEN_SNK,
    size = "medium",
)

library_test(
    name = "System.Runtime.CompilerServices.Unsafe.Tests",
    srcs = glob(["System.Runtime.CompilerServices.Unsafe.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.Runtime.CompilerServices.Unsafe:impl_System.Runtime.CompilerServices.Unsafe",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    allow_unsafe_blocks = True,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.Runtime.Handles.Tests",
    srcs = glob(["System.Runtime.Handles.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.Runtime.Handles:impl_System.Runtime.Handles",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.Security.SecureString.Tests",
    srcs = glob(["System.Security.SecureString.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.Security.SecureString:impl_System.Security.SecureString",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    allow_unsafe_blocks = True,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.ValueTuple.Tests",
    srcs = glob(["System.ValueTuple.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.ValueTuple:impl_System.ValueTuple",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.Diagnostics.Tools.Tests",
    srcs = glob(["System.Diagnostics.Tools.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.Diagnostics.Tools:impl_System.Diagnostics.Tools",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.Resources.Reader.Tests",
    srcs = glob(["System.Resources.Reader.Tests/**/*.cs"]),
    deps = [
        "//src/libraries/shims/System.Resources.Reader:impl_System.Resources.Reader",
        "//src/libraries/System.Resources.Writer:ref_System.Resources.Writer",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "small",
)

library_test(
    name = "System.Buffers.Tests",
    srcs = glob(["System.Buffers.Tests/**/*.cs"]) + [
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/TestEventListener.cs",
    ],
    deps = [
        "//src/libraries/shims/System.Buffers:impl_System.Buffers",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
    ] + XUNIT_DEPS,
    allow_unsafe_blocks = True,
    keyfile = OPEN_SNK,
    size = "medium",
)

library_test(
    name = "System.Threading.Timer.Tests",
    srcs = glob(["System.Threading.Timer.Tests/**/*.cs"]) + [
        "//src/libraries/Common/tests:System/Threading/ThreadTestHelpers.cs",
    ],
    deps = [
        "//src/libraries/shims/System.Threading.Timer:impl_System.Threading.Timer",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "medium",
)

library_test(
    name = "System.Threading.Tasks.Extensions.Tests",
    srcs = glob(["System.Threading.Tasks.Extensions.Tests/**/*.cs"]) + [
        "//src/libraries/Common/tests:System/Threading/Tasks/Sources/ManualResetValueTaskSource.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/Sources/ManualResetValueTaskSourceFactory.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/GetStateMachineData.cs",
    ],
    deps = [
        "//src/libraries/shims/System.Threading.Tasks.Extensions:impl_System.Threading.Tasks.Extensions",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/shims/System.Security:impl_System.Security",
        "//src/libraries:ref_System.Threading.Tasks",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "medium",
)

library_test(
    name = "System.Threading.Tasks.Tests",
    srcs = glob(["System.Threading.Tasks.Tests/**/*.cs"]) + [
        "//src/libraries/Common/tests:System/Diagnostics/Tracing/TestEventListener.cs",
        "//src/libraries/Common/tests:System/Threading/ThreadPoolHelpers.cs",
        "//src/libraries/Common/tests:System/Threading/Tasks/TaskTimeoutExtensions.cs",
    ],
    deps = [
        "//src/libraries/shims/System.Threading.Tasks:impl_System.Threading.Tasks",
        "//src/libraries/System.Collections.Concurrent:ref_System.Collections.Concurrent",
        "//src/libraries/System.Collections.Immutable:ref_System.Collections.Immutable",
        "//src/libraries/System.Diagnostics.Tracing:ref_System.Diagnostics.Tracing",
        "//src/libraries/System.Linq.AsyncEnumerable:ref_System.Linq.AsyncEnumerable",
        "//src/libraries/System.Linq.Expressions:ref_System.Linq.Expressions",
        "//src/libraries/System.Text.RegularExpressions:ref_System.Text.RegularExpressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries:ref_Microsoft.CSharp",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "large",
)

library_test(
    name = "System.Dynamic.Runtime.Tests",
    srcs = glob(["System.Dynamic.Runtime.Tests/**/*.cs"]),
    nowarn = [
        "67", "168", "219", "414", "162", "184", "458", "464",
        "78", "169", "114", "693", "108", "1981", "649", "109",
        "1066", "3021", "3026", "3002", "3014", "3022", "660",
        "661", "429", "xUnit1013",
    ],
    deps = [
        "//src/libraries:ref_Microsoft.CSharp",
        "//src/libraries/System.Linq.Expressions:ref_System.Linq.Expressions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    allow_unsafe_blocks = True,
    keyfile = OPEN_SNK,
    size = "large",
)

library_test(
    name = "System.Globalization.Calendars.Tests",
    srcs = glob(
        ["System.Globalization.Calendars.Tests/**/*.cs"],
        exclude = [
            "System.Globalization.Calendars.Tests/CalendarTestWithConfigSwitch/**",
            "System.Globalization.Calendars.Tests/Hybrid/**",
        ],
    ) + [
        "//src/libraries/Common/tests:System/RandomDataGenerator.cs",
    ],
    deps = [
        "//src/libraries/Common/tests:TestUtilities",
    ] + XUNIT_DEPS,
    keyfile = OPEN_SNK,
    size = "medium",
)

library_test(
    name = "System.IO.Tests",
    srcs = glob(["System.IO.Tests/**/*.cs"]) + [
        "//src/libraries/Common/tests:TestUtilities/System/DisableParallelization.cs",
        "//src/libraries/Common/tests:System/Buffers/NativeMemoryManager.cs",
        "//src/libraries/Common/tests:System/IO/CallTrackingStream.cs",
        "//src/libraries/Common/tests:System/IO/DelegateStream.cs",
        "//src/libraries/Common/tests:System/IO/WrappedMemoryStream.cs",
        "//src/libraries/Common/tests:System/IO/ConnectedStreams.cs",
        "//src/libraries/Common:src/System/Net/MultiArrayBuffer.cs",
        "//src/libraries/Common:src/System/Net/StreamBuffer.cs",
    ],
    deps = [
        "//src/libraries/shims/System.IO:impl_System.IO",
        "//src/libraries/System.IO.Pipes:ref_System.IO.Pipes",
        "//src/libraries/System.Security.Cryptography:ref_System.Security.Cryptography",
        "//src/libraries/System.Text.Encoding.CodePages:ref_System.Text.Encoding.CodePages",
        "//src/libraries/System.Text.Encoding.Extensions:ref_System.Text.Encoding.Extensions",
        "//src/libraries/System.Threading:ref_System.Threading",
        "//src/libraries/System.Threading.Thread:ref_System.Threading.Thread",
        "//src/libraries/System.Threading.ThreadPool:ref_System.Threading.ThreadPool",
        "//src/libraries/System.Threading.Tasks.Parallel:ref_System.Threading.Tasks.Parallel",
        "//src/libraries/Common/tests:StreamConformanceTests",
        "//src/libraries/Common/tests:TestUtilities",
        "@paket.main//microsoft.dotnet.remoteexecutor",
    ] + XUNIT_DEPS,
    allow_unsafe_blocks = True,
    keyfile = OPEN_SNK,
    size = "large",
)
