
load(
    "//:defs.bzl",
    "OPEN_SNK",
    "csharp_library"
)

exports_files([
    "ref/System.Private.CoreLib.ExtraApis.cs",
    "ref/System.Private.CoreLib.ManualShimTypeForwards.cs",
    "src/Resources/Strings.resx",
])
exports_files(glob(["src/**/*.cs"]))

csharp_library(
    name = "System.Private.CoreLib.Generators",
    keyfile = OPEN_SNK,
    srcs = glob(["gen/*.cs"]) + [
        "//src/libraries/System.Private.CoreLib:src/System/Runtime/CompilerServices/IsExternalInit.cs",
        "//src/libraries/System.Private.CoreLib:src/System/Collections/Generic/ValueListBuilder.cs",
        "//src/libraries/System.Private.CoreLib:src/System/Collections/Generic/ValueListBuilder.Pop.cs",
    ],
    target_frameworks = ["netstandard2.0"],
    langversion = "preview",
    nullable = "enable",
    deps = [
        "@paket.main//microsoft.codeanalysis.common",
        "@paket.main//microsoft.codeanalysis.csharp",
        "@paket.illink//system.numerics.vectors",
        "@paket.main//system.collections.immutable",
        "@paket.main//system.memory",
        "@paket.main//system.buffers",
        "@paket.main//system.reflection.metadata",
        "@paket.main//system.runtime.compilerservices.unsafe",
        "@paket.illink//system.text.encoding.codepages",
        "@paket.illink//system.threading.tasks.extensions",
    ],
    analyzers = [
        "//:source_build_analyzers",
    ],
    msbuild_analyzer_config = "source",
    include_syslib_warnaserror = False,
    extra_editorconfig_content = "dotnet_diagnostic.RS1036.severity = none",
    nowarn = [
        "CS3001",
        "CS3021",
        "CS1591",
        "nullable",
    ],
    defines = ["BAZEL"],
    visibility = ["//visibility:public"],
)
