// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_Runtime_105944_runtime_105944 = CoreClr.coreclr_test({
    name: "Runtime_105944",
    srcs: ["Runtime_105944.cs", "//src/libraries/Common/tests:TestUtilities/System/Buffers/BoundedMemory.cs", "//src/libraries/Common/tests:TestUtilities/System/Buffers/BoundedMemory.Creation.cs", "//src/libraries/Common/tests:TestUtilities/System/Buffers/BoundedMemory.Unix.cs", "//src/libraries/Common/tests:TestUtilities/System/Buffers/BoundedMemory.Windows.cs", "//src/libraries/Common/tests:TestUtilities/System/Buffers/BoundedMemory.Default.cs", "//src/libraries/Common/tests:TestUtilities/System/Buffers/PoisonPagePlacement.cs"],
    allowUnsafe: true,
    compilerOptions: ["/nowarn:SYSLIB5003"],
    optimize: true,
});
