// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const regressions_coreclr_GitHub_49982_test49982 = CoreClr.coreclr_test({
    name: "test49982",
    srcs: ["test49982.cs"],
    nullable: "enable",
    pri: 1,
});
